# Generated by Django 3.1 on 2020-09-03 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_module_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='students',
        ),
    ]
